#começando tratamento de dados

In [242]:
import pandas as pd

In [243]:
data = pd.read_csv("C:\\Users\\Usuario\\Downloads\\Cópia V1 de Solicitações SIC - Cardápios - cardapio.csv")

In [244]:
data["date"] = pd.to_datetime(data["date"], dayfirst=True)

dataf = data[data["date"] >= "2024-02-28"]
dataf

C:\Users\Usuario\AppData\Local\Temp\ipykernel_11720\87926198.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  data["date"] = pd.to_datetime(data["date"], dayfirst=True)

,date,refeicao,acompanhamento,prato,guarnicao,opcao_vegetal,salada,sobremesa,suco
0,2025-08-15,Almoço - Cardápio Padrão,ARROZ E FEIJÃO,"PUCHERO (CUBOS SUÍNO, LINGUIÇA CALABRESA, CENO...",VIRADO DE COUVE,NaN,SALADA DE REPOLHO VERDE E ROXO,LARANJA,REFRESCO SABOR GOIABA
1,2025-08-15,Almoço - Cardápio Vegano,ARROZ INTEGRAL E FEIJÃO,FEIJÃO BRANCO COM BRÓCOLIS E QUINOA,VIRADO DE COUVE,NaN,SALADA DE REPOLHO VERDE E ROXO,LARANJA,REFRESCO DE GOIABA
2,2025-08-15,Jantar - Cardápio Padrão,ARROZ E FEIJÃO,SOBRECOXA DE FRANGO ASSADA,"LEGUMES À PORTUGUESA (BATATA, CEBOLA EM RODELA...",NaN,SALADA DE ESCAROLA,ABACAXI EM CALDA,REFRESCO DE GOIABA
3,2025-08-15,Jantar - Cardápio Vegano,ARROZ INTEGRAL E FEIJÃO,"ERVILHA TORTA ENSOPADA COM ABÓBORA SECA, PALMI...","LEGUMES À PORTUGUESA (BATATA, CEBOLA EM RODELA...",NaN,SALADA DE ESCAROLA,ABACAXI EM CALDA,REFRESCO DE GOIABA
4,2025-08-14,Almoço - Cardápio Padrão,ARROZ E FEIJÃO,FRICASSÊ DE FRANGO,"ARROZ COLORIDO (ERVILHA, MILHO, CENOURA E SALSA)",NaN,SALADA DE BETERRABA RALADA (RS /HC / CAISM) SA...,SAGU DE UVA,REFRESCO DE LARANJA
...,...,...,...,...,...,...,...,...,...
1907,2024-02-29,Jantar - Cardápio Vegano,ARROZ INTEGRAL E FEIJÃO,"ESCONDIDINHO VEGANO (PTS, MILHO E ERVILHA)",ABOBRINHA COM ERVAS,NaN,SALADA DE BETERRABA COZIDA,MAÇÃ,REFRESCO DE MORANGO
1908,2024-02-28,Almoço - Cardápio Padrão,ARROZ E FEIJÃO,LAGARTO ASSADO AO VINAGRETE,POLENTA CREMOSA,NaN,SALADA DE REPOLHO BRANCO COM REPOLHO ROXO,BANANA,REFRESCO DE FRAMBOESA
1909,2024-02-28,Almoço - Cardápio Vegano,ARROZ INTEGRAL E FEIJÃO,LENTILHA COM CHUCHU E ABÓBORA,POLENTA CREMOSA,NaN,SALADA DE REPOLHO BRANCO COM REPOLHO ROXO,BANANA,REFRESCO DE FRAMBOESA
1910,2024-02-28,Jantar - Cardápio Padrão,ARROZ E FEIJÃO,SALSICHA AO SUGO,"JARDINEIRA DE LEGUMES (VAGEM, CENOURA E BATATA)",NaN,SALADA DE ALFACE COM RÚCULA,"MELANCIA (RU, RS e HC) / MAÇÃ (RA)",REFRESCO DE FRAMBOESA
1911,2024-02-28,Jantar - Cardápio Vegano,ARROZ INTEGRAL E FEIJÃO,YAKISOBA VEGANO COM ERVILHA PARTIDA,ESCAROLA REFOGADA,NaN,SALADA DE ALFACE COM RÚCULA,"MELANCIA (RU, RS e HC) / MAÇÃ (RA)",REFRESCO DE FRAMBOESA

In [245]:
dataf["refeicao"].unique()

array(['Almoço - Cardápio Padrão', 'Almoço - Cardápio Vegano',
       'Jantar - Cardápio Padrão', 'Jantar - Cardápio Vegano'],
      dtype=object)

In [246]:
# 0 = Almoço, 1 = Jantar
dataf["almoco_janta"] = dataf["refeicao"].str.contains("Jantar").astype(int)

# 0 = Padrão, 1 = Vegano
dataf["vegano"] = dataf["refeicao"].str.contains("Vegano").astype(int)
dataf

,date,refeicao,acompanhamento,prato,guarnicao,opcao_vegetal,salada,sobremesa,suco,almoco_janta,vegano
0,2025-08-15,Almoço - Cardápio Padrão,ARROZ E FEIJÃO,"PUCHERO (CUBOS SUÍNO, LINGUIÇA CALABRESA, CENO...",VIRADO DE COUVE,NaN,SALADA DE REPOLHO VERDE E ROXO,LARANJA,REFRESCO SABOR GOIABA,0,0
1,2025-08-15,Almoço - Cardápio Vegano,ARROZ INTEGRAL E FEIJÃO,FEIJÃO BRANCO COM BRÓCOLIS E QUINOA,VIRADO DE COUVE,NaN,SALADA DE REPOLHO VERDE E ROXO,LARANJA,REFRESCO DE GOIABA,0,1
2,2025-08-15,Jantar - Cardápio Padrão,ARROZ E FEIJÃO,SOBRECOXA DE FRANGO ASSADA,"LEGUMES À PORTUGUESA (BATATA, CEBOLA EM RODELA...",NaN,SALADA DE ESCAROLA,ABACAXI EM CALDA,REFRESCO DE GOIABA,1,0
3,2025-08-15,Jantar - Cardápio Vegano,ARROZ INTEGRAL E FEIJÃO,"ERVILHA TORTA ENSOPADA COM ABÓBORA SECA, PALMI...","LEGUMES À PORTUGUESA (BATATA, CEBOLA EM RODELA...",NaN,SALADA DE ESCAROLA,ABACAXI EM CALDA,REFRESCO DE GOIABA,1,1
4,2025-08-14,Almoço - Cardápio Padrão,ARROZ E FEIJÃO,FRICASSÊ DE FRANGO,"ARROZ COLORIDO (ERVILHA, MILHO, CENOURA E SALSA)",NaN,SALADA DE BETERRABA RALADA (RS /HC / CAISM) SA...,SAGU DE UVA,REFRESCO DE LARANJA,0,0
...,...,...,...,...,...,...,...,...,...,...,...
1907,2024-02-29,Jantar - Cardápio Vegano,ARROZ INTEGRAL E FEIJÃO,"ESCONDIDINHO VEGANO (PTS, MILHO E ERVILHA)",ABOBRINHA COM ERVAS,NaN,SALADA DE BETERRABA COZIDA,MAÇÃ,REFRESCO DE MORANGO,1,1
1908,2024-02-28,Almoço - Cardápio Padrão,ARROZ E FEIJÃO,LAGARTO ASSADO AO VINAGRETE,POLENTA CREMOSA,NaN,SALADA DE REPOLHO BRANCO COM REPOLHO ROXO,BANANA,REFRESCO DE FRAMBOESA,0,0
1909,2024-02-28,Almoço - Cardápio Vegano,ARROZ INTEGRAL E FEIJÃO,LENTILHA COM CHUCHU E ABÓBORA,POLENTA CREMOSA,NaN,SALADA DE REPOLHO BRANCO COM REPOLHO ROXO,BANANA,REFRESCO DE FRAMBOESA,0,1
1910,2024-02-28,Jantar - Cardápio Padrão,ARROZ E FEIJÃO,SALSICHA AO SUGO,"JARDINEIRA DE LEGUMES (VAGEM, CENOURA E BATATA)",NaN,SALADA DE ALFACE COM RÚCULA,"MELANCIA (RU, RS e HC) / MAÇÃ (RA)",REFRESCO DE FRAMBOESA,1,0
1911,2024-02-28,Jantar - Cardápio Vegano,ARROZ INTEGRAL E FEIJÃO,YAKISOBA VEGANO COM ERVILHA PARTIDA,ESCAROLA REFOGADA,NaN,SALADA DE ALFACE COM RÚCULA,"MELANCIA (RU, RS e HC) / MAÇÃ (RA)",REFRESCO DE FRAMBOESA,1,1

In [247]:
dataf.columns.unique()

Index(['date', 'refeicao', 'acompanhamento', 'prato', 'guarnicao',
       'opcao_vegetal', 'salada', 'sobremesa', 'suco', 'almoco_janta',
       'vegano'],
      dtype='object')

In [248]:
dataf
dataf = dataf.drop(columns=['salada',"acompanhamento","guarnicao",'opcao_vegetal','sobremesa','suco'])
dataf

,date,refeicao,prato,almoco_janta,vegano
0,2025-08-15,Almoço - Cardápio Padrão,"PUCHERO (CUBOS SUÍNO, LINGUIÇA CALABRESA, CENO...",0,0
1,2025-08-15,Almoço - Cardápio Vegano,FEIJÃO BRANCO COM BRÓCOLIS E QUINOA,0,1
2,2025-08-15,Jantar - Cardápio Padrão,SOBRECOXA DE FRANGO ASSADA,1,0
3,2025-08-15,Jantar - Cardápio Vegano,"ERVILHA TORTA ENSOPADA COM ABÓBORA SECA, PALMI...",1,1
4,2025-08-14,Almoço - Cardápio Padrão,FRICASSÊ DE FRANGO,0,0
...,...,...,...,...,...
1907,2024-02-29,Jantar - Cardápio Vegano,"ESCONDIDINHO VEGANO (PTS, MILHO E ERVILHA)",1,1
1908,2024-02-28,Almoço - Cardápio Padrão,LAGARTO ASSADO AO VINAGRETE,0,0
1909,2024-02-28,Almoço - Cardápio Vegano,LENTILHA COM CHUCHU E ABÓBORA,0,1
1910,2024-02-28,Jantar - Cardápio Padrão,SALSICHA AO SUGO,1,0
1911,2024-02-28,Jantar - Cardápio Vegano,YAKISOBA VEGANO COM ERVILHA PARTIDA,1,1

In [249]:
dataf["date"] = pd.to_datetime(dataf["date"], dayfirst=True, errors="coerce")
dataf

,date,refeicao,prato,almoco_janta,vegano
0,2025-08-15,Almoço - Cardápio Padrão,"PUCHERO (CUBOS SUÍNO, LINGUIÇA CALABRESA, CENO...",0,0
1,2025-08-15,Almoço - Cardápio Vegano,FEIJÃO BRANCO COM BRÓCOLIS E QUINOA,0,1
2,2025-08-15,Jantar - Cardápio Padrão,SOBRECOXA DE FRANGO ASSADA,1,0
3,2025-08-15,Jantar - Cardápio Vegano,"ERVILHA TORTA ENSOPADA COM ABÓBORA SECA, PALMI...",1,1
4,2025-08-14,Almoço - Cardápio Padrão,FRICASSÊ DE FRANGO,0,0
...,...,...,...,...,...
1907,2024-02-29,Jantar - Cardápio Vegano,"ESCONDIDINHO VEGANO (PTS, MILHO E ERVILHA)",1,1
1908,2024-02-28,Almoço - Cardápio Padrão,LAGARTO ASSADO AO VINAGRETE,0,0
1909,2024-02-28,Almoço - Cardápio Vegano,LENTILHA COM CHUCHU E ABÓBORA,0,1
1910,2024-02-28,Jantar - Cardápio Padrão,SALSICHA AO SUGO,1,0
1911,2024-02-28,Jantar - Cardápio Vegano,YAKISOBA VEGANO COM ERVILHA PARTIDA,1,1

In [250]:
dataf=dataf.drop(columns=["refeicao"])
dataf

,date,prato,almoco_janta,vegano
0,2025-08-15,"PUCHERO (CUBOS SUÍNO, LINGUIÇA CALABRESA, CENO...",0,0
1,2025-08-15,FEIJÃO BRANCO COM BRÓCOLIS E QUINOA,0,1
2,2025-08-15,SOBRECOXA DE FRANGO ASSADA,1,0
3,2025-08-15,"ERVILHA TORTA ENSOPADA COM ABÓBORA SECA, PALMI...",1,1
4,2025-08-14,FRICASSÊ DE FRANGO,0,0
...,...,...,...,...
1907,2024-02-29,"ESCONDIDINHO VEGANO (PTS, MILHO E ERVILHA)",1,1
1908,2024-02-28,LAGARTO ASSADO AO VINAGRETE,0,0
1909,2024-02-28,LENTILHA COM CHUCHU E ABÓBORA,0,1
1910,2024-02-28,SALSICHA AO SUGO,1,0
1911,2024-02-28,YAKISOBA VEGANO COM ERVILHA PARTIDA,1,1

In [251]:
dataf["prato"].value_counts()

prato
FILEZINHO DE FRANGO ACEBOLADO                21
STROGONOFF VEGANO (PTS)                      20
FEIJOADA                                     18
STROGONOFF DE CARNE                          17
BIFE ACEBOLADO                               16
                                             ..
LENTILHA COM TOMATE                           1
LINGUIÇA DE FRANGO ACEBOLADA                  1
FEIJÃO BRANCO COM BATATA, TOMATE E CEBOLA     1
CARNE EM CUBOS COM BATATA                     1
SOBRECOXA DE PANELA NA SALSA                  1
Name: count, Length: 1147, dtype: int64

In [252]:
# dicionário de palavras-chave -> categoria
categorias = {
    "frango": ["frango", "sobrecoxa", "nugget", "sassami"],
    "bovino": ["boi", "bovino", "bife", "carne", "lagarto", "iscas bovinas", "acém", "patinho", "almôndega"],
    "peixe": ["peixe", "tilápia", "pescada"],
    "suino": ["suíno", "bisteca", "suína", "pernil", "linguiça toscana", "copa lombo"],
    "bovino e suino": ["bovinos e suínos", "salsicha"],
    "feijoada": ["feijoada"],
    "ovo": ["fritada", "omelete"]
}

# função para categorizar
def categoriza(prato):
    if pd.isna(prato):  # handle NaN values
        return "outros"
    
    prato_lower = str(prato).lower()  # convert to string and lowercase
    for categoria, palavras in categorias.items():
        for palavra in palavras:
            if palavra in prato_lower:
                return categoria
    return "outros"

# aplica direto na coluna do seu dataframe
dataf["categoria"] = dataf["prato"].apply(categoriza)

# visualiza o resultado
print(dataf[["prato", "categoria"]])

                                                  prato       categoria
0     PUCHERO (CUBOS SUÍNO, LINGUIÇA CALABRESA, CENO...           suino
1                   FEIJÃO BRANCO COM BRÓCOLIS E QUINOA          outros
2                            SOBRECOXA DE FRANGO ASSADA          frango
3     ERVILHA TORTA ENSOPADA COM ABÓBORA SECA, PALMI...          outros
4                                    FRICASSÊ DE FRANGO          frango
...                                                 ...             ...
1907         ESCONDIDINHO VEGANO (PTS, MILHO E ERVILHA)          outros
1908                        LAGARTO ASSADO AO VINAGRETE          bovino
1909                      LENTILHA COM CHUCHU E ABÓBORA          outros
1910                                   SALSICHA AO SUGO  bovino e suino
1911                YAKISOBA VEGANO COM ERVILHA PARTIDA          outros

[1912 rows x 2 columns]

In [253]:
dataf

,date,prato,almoco_janta,vegano,categoria
0,2025-08-15,"PUCHERO (CUBOS SUÍNO, LINGUIÇA CALABRESA, CENO...",0,0,suino
1,2025-08-15,FEIJÃO BRANCO COM BRÓCOLIS E QUINOA,0,1,outros
2,2025-08-15,SOBRECOXA DE FRANGO ASSADA,1,0,frango
3,2025-08-15,"ERVILHA TORTA ENSOPADA COM ABÓBORA SECA, PALMI...",1,1,outros
4,2025-08-14,FRICASSÊ DE FRANGO,0,0,frango
...,...,...,...,...,...
1907,2024-02-29,"ESCONDIDINHO VEGANO (PTS, MILHO E ERVILHA)",1,1,outros
1908,2024-02-28,LAGARTO ASSADO AO VINAGRETE,0,0,bovino
1909,2024-02-28,LENTILHA COM CHUCHU E ABÓBORA,0,1,outros
1910,2024-02-28,SALSICHA AO SUGO,1,0,bovino e suino
1911,2024-02-28,YAKISOBA VEGANO COM ERVILHA PARTIDA,1,1,outros

In [254]:
dataf["categoria"].value_counts()

categoria
outros            928
bovino            402
frango            300
suino             130
peixe             105
feijoada           36
ovo                 8
bovino e suino      3
Name: count, dtype: int64

In [255]:
data2 = dataf.drop(dataf[dataf["vegano"] == 1].index)
data2.to_csv("arquivo_filtrado.csv", index=False)

In [256]:
data2["categoria"].value_counts()

categoria
bovino            389
frango            300
suino             130
peixe             105
feijoada           18
outros              5
ovo                 5
bovino e suino      3
Name: count, dtype: int64

In [257]:
data2

,date,prato,almoco_janta,vegano,categoria
0,2025-08-15,"PUCHERO (CUBOS SUÍNO, LINGUIÇA CALABRESA, CENO...",0,0,suino
2,2025-08-15,SOBRECOXA DE FRANGO ASSADA,1,0,frango
4,2025-08-14,FRICASSÊ DE FRANGO,0,0,frango
6,2025-08-14,PESCADA AO MOLHO DE ERVAS,1,0,peixe
8,2025-08-13,PESCADA AO MOLHO DE AZEITONAS,0,0,peixe
...,...,...,...,...,...
1902,2024-03-01,BIFE AO MOLHO FERRUGEM (TOMATE E MOLHO INGLÊS),1,0,bovino
1904,2024-02-29,FILEZINHO DE FRANGO GRELHADO AO MOLHO DE TOMATE,0,0,frango
1906,2024-02-29,LAGARTO ASSADO AO ALHO PORÓ,1,0,bovino
1908,2024-02-28,LAGARTO ASSADO AO VINAGRETE,0,0,bovino
1910,2024-02-28,SALSICHA AO SUGO,1,0,bovino e suino

In [258]:
# filtra e cria um novo DataFrame
data2 = data2[data2["categoria"] == "outros"]

# visualiza o resultado
print(data2)

# se quiser salvar em CSV
data2.to_csv("data2_filtrado.csv", index=False)

           date     prato  almoco_janta  vegano categoria
78   2025-07-25  FEIJOADA             0       0  feijoada
79   2025-07-25  FEIJOADA             1       0  feijoada
180  2025-06-27  FEIJOADA             0       0  feijoada
182  2025-06-27  FEIJOADA             1       0  feijoada
282  2025-05-30  FEIJOADA             0       0  feijoada
284  2025-05-30  FEIJOADA             1       0  feijoada
360  2025-05-09  FEIJOADA             0       0  feijoada
362  2025-05-09  FEIJOADA             1       0  feijoada
1321 2024-08-16  FEIJOADA             0       0  feijoada
1323 2024-08-16  FEIJOADA             1       0  feijoada
1425 2024-07-19  FEIJOADA             0       0  feijoada
1427 2024-07-19  FEIJOADA             1       0  feijoada
1527 2024-06-21  FEIJOADA             0       0  feijoada
1529 2024-06-21  FEIJOADA             1       0  feijoada
1655 2024-05-17  FEIJOADA             0       0  feijoada
1657 2024-05-17  FEIJOADA             1       0  feijoada
1783 2024-04-12  FEIJOADA             0       0  feijoada
1785 2024-04-12  FEIJOADA             1       0  feijoada

In [259]:
data2

           date     prato  almoco_janta  vegano categoria
78   2025-07-25  FEIJOADA             0       0  feijoada
79   2025-07-25  FEIJOADA             1       0  feijoada
180  2025-06-27  FEIJOADA             0       0  feijoada
182  2025-06-27  FEIJOADA             1       0  feijoada
282  2025-05-30  FEIJOADA             0       0  feijoada
284  2025-05-30  FEIJOADA             1       0  feijoada
360  2025-05-09  FEIJOADA             0       0  feijoada
362  2025-05-09  FEIJOADA             1       0  feijoada
1321 2024-08-16  FEIJOADA             0       0  feijoada
1323 2024-08-16  FEIJOADA             1       0  feijoada
1425 2024-07-19  FEIJOADA             0       0  feijoada
1427 2024-07-19  FEIJOADA             1       0  feijoada
1527 2024-06-21  FEIJOADA             0       0  feijoada
1529 2024-06-21  FEIJOADA             1       0  feijoada
1655 2024-05-17  FEIJOADA             0       0  feijoada
1657 2024-05-17  FEIJOADA             1       0  feijoada
1783 2024-04-12  FEIJOADA             0       0  feijoada
1785 2024-04-12  FEIJOADA             1       0  feijoada

In [231]:
data2["prato"].unique()

array([], dtype=object)

In [289]:
# Filtra apenas os pratos veganos (baseado na coluna 'refeicao')
pratos_veganos = data[data["refeicao"].str.contains("Vegano", case=False)]["prato"].unique() # Cria um DataFrame para visualização tabela_veganos = pd.DataFrame({ 'prato_vegano': pratos_veganos })

In [290]:
# dicionário de palavras-chave -> categoria VEGANA (atualizado)
categorias_veganas = {
    "pts_proteina_texturizada": ["pts", "proteína texturizada", "almôndega vegana", "strogonoff vegano", "quibe de pts", "fricassê de pts", "fricassê vegano"],
    "leguminosas": ["feijão", "lentilha", "grão-de-bico", "ervilha", "soja", "grão de bico", "feijão branco", "fradinho", "mix de feijões", "letilha"],
    "cereais_integrais": ["arroz integral", "quinoa", "aveia", "trigo", "cevada", "milho", "arroz 7 grãos", "cuzcuz", "cuscuz"],
    "vegetais": ["quibe de abóbora", "quibe de brócolis"],
    "feijoada_vegana": ["feijoada"]
}

# função para categorizar PRATOS VEGANOS
def categoriza_vegano(prato):
    if pd.isna(prato):  # handle NaN values
        return "outros"
    
    prato_lower = str(prato).lower()  # convert to string and lowercase
    
    # Verifica combinações específicas primeiro
    for categoria, palavras in categorias_veganas.items():
        for palavra in palavras:
            if palavra in prato_lower:
                return categoria
    
    return "outros"

# aplica a categorização atualizada
data_vegana["categoria_vegana"] = data_vegana["prato"].apply(categoriza_vegano)

# verifica os resultados
print("Categorização atualizada:")
resultados = data_vegana[["prato", "categoria_vegana"]].drop_duplicates()
print(resultados.head(30))

print("\nDistribuição após atualização:")
print(data_vegana["categoria_vegana"].value_counts())

Categorização atualizada:
                                                prato  \
1                 FEIJÃO BRANCO COM BRÓCOLIS E QUINOA
3   ERVILHA TORTA ENSOPADA COM ABÓBORA SECA, PALMI...
5                       FRICASSÊ DE PTS COM BERINJELA
7                            GRÃO DE BICO AO POMODORO
9          SOJA EM GRÃOS ENSOPADA COM QUIABO E TOMATE
11  LENTILHA COM COUVE-FLOR AO VINAGRETE (RA/RS) |...
13  MIX DE LENTILHA E SOJA EM GRÃO COM ABÓBORA CAB...
15                         PTS REFOGADA COM BATERRABA
17  PTS COM MILHO E ERVILHA (RU / RA / RS) - HAMBÚ...
19   FEIJÃO BRANCO RÚSTICO (CHUCHU, ABÓBORA E TOMATE)
21                      PTS COM ERVILHA, MILHO E CARÁ
23                 LENTILHA GRATINADA COM BATATA DOCE
25                      SOJA COM MANDIOQUINHA AO SUGO
27                        QUIBE DE GRÃO DE BICO E PTS
29                        BERINJELA GRATINADA COM PTS
31                     PTS COM CHUCHU AO MOLHO ESCURO
33                     TORTA DE LENTILHA COM ESCAROLA
35  SOJA EM GRÃOS AO SUGO COM AZEITONAS, MILHO E C...
37  ERVILHA COM GRÃOS DE TRIGO E COUVE-FLOR GRATIN...
39                                MOQUECA DE ERVILHAS
41  LENTILHA COM LEGUMES (ABOBRINHA, CENOURA E MILHO)
43                         STROGONOFF DE GRÃO DE BICO
45                          MACARRÃO COM PTS AO SHOYU
47       FEIJÃO BRANCO COM CENOURA E SALSINHA AO SUGO
49  FEIJÃO FRADINHO COM QUIABO, BATATA, AZEITONAS ...
53                          QUIBE DE PTS COM BRÓCOLIS
55                              TORTA DE GRÃO DE BICO
57                        ERVILHA PARTIDA COM CENOURA
59  RISOTO ESPECIAL (ARROZ BRANCO, TRIGO EM GRÃOS,...
61                             LENTILHA COM BERINJELA

            categoria_vegana
1                leguminosas
3                leguminosas
5   pts_proteina_texturizada
7                leguminosas
9                leguminosas
11  pts_proteina_texturizada
13               leguminosas
15  pts_proteina_texturizada
17  pts_proteina_texturizada
19               leguminosas
21  pts_proteina_texturizada
23               leguminosas
25               leguminosas
27  pts_proteina_texturizada
29  pts_proteina_texturizada
31  pts_proteina_texturizada
33               leguminosas
35               leguminosas
37               leguminosas
39               leguminosas
41               leguminosas
43               leguminosas
45  pts_proteina_texturizada
47               leguminosas
49               leguminosas
53  pts_proteina_texturizada
55               leguminosas
57               leguminosas
59  pts_proteina_texturizada
61               leguminosas

Distribuição após atualização:
categoria_vegana
leguminosas                 656
pts_proteina_texturizada    282
outros                        7
cereais_integrais             5
feijoada_vegana               4
vegetais                      3
Name: count, dtype: int64

In [282]:
# Primeiro veja quais pratos estão sendo classificados como "outros"
outros_pratos = data_vegana[data_vegana["categoria_vegana"] == "outros"]["prato"].unique()

print("Pratos que precisam de categorização manual:")
for prato in outros_pratos:
    print(f"• {prato}")

# Baseado nisso, você pode adicionar novas palavras-chave ao dicionário

Pratos que precisam de categorização manual:
• FRICASSÊ DE BERINJELA
• YAKISSOBA VEGANO

In [285]:
# Filtrar todas as feijoadas (independente de ser padrão ou vegano)
mask = data["prato"].str.contains("feijoada", case=False, na=False)
feijoadas = data[mask]

# Agora separar padrão e vegano pela coluna 'refeicao'
feijoada_padrao = feijoadas[feijoadas["refeicao"].str.contains("Padrão", case=False, na=False)]
feijoada_vegana = feijoadas[feijoadas["refeicao"].str.contains("Vegano", case=False, na=False)]

print("Feijoadas Tradicionais:", len(feijoada_padrao))
print("Feijoadas Veganas:", len(feijoada_vegana))

# Se quiser ver os nomes exatos das feijoadas veganas
print(feijoada_vegana["prato"].unique())

Feijoadas Tradicionais: 18
Feijoadas Veganas: 18
['FEIJOADA VEGANA (PTS)' 'FEIJOADA VEGANA'
 'FEIJOADA VEGANA (PTS, ABÓBORA JAPONESA, BETERRABA, CHUCHU, MANDIOQUINHA)'
 'FEIJOADA  VEGANA (PTS, ABÓBORA JAPONESA, BETERRABA, CHUCHU, MANDIOQUINHA)'
 'FEIJOADA VEGANA (COM PTS)']